### PR TITLE
FIX: Loader not showing in sign in or sign up and page title

### PR DESCRIPTION
**Pull request by UmeshKumar0143**
fixes : #24 

Fixed the loader not showing on clicking sign in or sign up  and title of the app to pen craft 

video : 

https://github.com/user-attachments/assets/7e74e86c-6dcb-4ba6-af30-6d932949752f

### CODE REVIEW

**Comment by AkshitLakhera** [comment]
@UmeshKumar0143  I want  you add a spinning loader with singingup and  design customized error popup.

**Comment by UmeshKumar0143** [comment]
Is this loader ok ? 

https://github.com/user-attachments/assets/68dc9ef7-ade5-4166-aa4a-6a1787759b3f

**Comment by AkshitLakhera** [comment]
> @AkshitLakhera Is this loader ok ?
> 2024-10-02.16-52-38.mp4

Yes it is fine.

**Comment by UmeshKumar0143** [comment]
Will this error message work @AkshitLakhera 
image

**Comment by UmeshKumar0143** [comment]
Will this error message work @AkshitLakhera ? 
image

**Pull request merged**
