### PR TITLE
X Logo Added | Issue #109

### PR DESCRIPTION
**Pull request by Shariq2003**
I replace the twitter logo with X logo.

Completed #109 

image
image

### CODE REVIEW

**Comment by Shariq2003** [comment]
@AkshitLakhera please review and merge

**Comment by AkshitLakhera** [comment]
@Shariq2003  why added and removed these many lines for such a small change.Always try to minimize this.

**Comment by AkshitLakhera** [comment]
@Shariq2003   make pr ,with only the changes you made ,don't touch rest of code .As it is make's the reviewer job tough to review it.

**Comment by Shariq2003** [comment]
> @Shariq2003 why added and removed these many lines for such a small change.Always try to minimize this.

No, I just change the svg, and the other are only the auto structuring of vs code

**Comment by Shariq2003** [comment]
@AkshitLakhera sir, i am raising new PR and closing this one

**Pull request closed without merging**
