### PR TITLE
added google translator

### LINKED ISSUE #130: [FEATURE] [Add Multi-Language Support for Global Accessibility]
**Is your feature request related to a problem? Please describe.**
Implement multi-language support , allowing users from different regions to interact with the website in their preferred language. This feature will enhance accessibility and usability, making it easier for non-English-speaking users to browse the site.

**Describe the solution you'd like**
Set up a language selection dropdown or toggle in the header/footer for easy switching.
Store language preferences using cookies or local storage.
Ensure that the translated content adapts dynamically based on the selected language.

**Describe alternatives you've considered**

**Additional context**
please assign this to me under gssoc-ext and hacktoberfest

### PR DESCRIPTION
**Pull request by sezallagwal**
closes #130 

https://github.com/user-attachments/assets/0873517d-9410-4a80-b746-de72dbe92d79

please review this pr @AkshitLakhera
Thanks!

### CODE REVIEW

**Comment by sezallagwal** [comment]
@AkshitLakhera hey its been 2 days Can you please review and merge it

**Comment by AkshitLakhera** [comment]
@sezallagwal  I am really sorry for inconvenience  caused as I was in hospital with my grandmother.

**Comment by AkshitLakhera** [comment]
@sezallagwal  great job

**Comment by sezallagwal** [comment]
@AkshitLakhera no worries at all. I hope your grandmother is doing better now.

**Comment by AkshitLakhera** [comment]
> @AkshitLakhera no worries at all. I hope your grandmother is doing better now.

She is fine now ,thank you for showing your concern.

**Pull request merged**
