### PR TITLE
Added the Contributor page to /contributor route with proper theme and structure.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
Added the Contributor page to /contributor route with proper theme and structure.

closes :- #92 

https://github.com/user-attachments/assets/c7cf81fe-517a-432b-8e11-69c1ce6a5ec0

@AkshitLakhera Check this PR and merge it and assign this to me and put relevant labels to it like gssoc 2024 ext, hacktoberfest and level. i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this.

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
@AkshitLakhera Can you check the PR and merge it (reminder)

**Comment by tarunkumar2005** [comment]
@AkshitLakhera Check the PR pending from 4 days (reminder)

**Comment by AkshitLakhera** [comment]
> @AkshitLakhera Check the PR pending from 4 days (reminder)

sorry for inconvenience I was busy with my exams.It is looking great

**Comment by tarunkumar2005** [comment]
@AkshitLakhera Please put it level 3 it is fully responsive on all screen sizes and functional and dynamic also.

**Pull request merged**
