### PR TITLE
Fixes #111: Height of Landing Page

### LINKED ISSUE #111: Height of Landing Page
you need to scroll down on the homepage to login. I want to fix the height of the landing page to size of viewport to enhance UI.
@AkshitLakhera 
please add gssoc-ext and hacktoberfest-accepted labels

image

### PR DESCRIPTION
**Pull request by jainaryan04**
@AkshitLakhera please add gssoc-ext label.

### CODE REVIEW

**Comment by jainaryan04** [comment]
@AkshitLakhera please merge

**Comment by AkshitLakhera** [comment]
@jainaryan04  resolve merge conflicts first , Then I will merge it

**Comment by jainaryan04** [comment]
done @AkshitLakhera

**Comment by jainaryan04** [comment]
@AkshitLakhera

**Comment by jainaryan04** [comment]
@AkshitLakhera hi. last 2 days for gssoc. please merge asap.

**Comment by jainaryan04** [comment]
@AkshitLakhera  hi. last 2 days for gssoc. please merge asap.

**Pull request merged**
