### PR TITLE
Added X Logo | Issue #109

### PR DESCRIPTION
**Pull request by Shariq2003**
I replace the twitter logo with X logo.

Completed #109 

image
image

### CODE REVIEW

**Comment by Shariq2003** [comment]
@AkshitLakhera sir, please review and merge

**Comment by Shariq2003** [comment]
@MastanSayyad sir please review and merge this

**Comment by Shariq2003** [comment]
> Too many extra spaces + same SVG, level 1 can be given
> 
> also @Shariq2003 no need to tag me in each PR, I'm reviewing other contributors os this is interfering the process as said , take a not of each PR in a file with links and issue number.

Yes, its if of level 1, also in have updated the SVG of Twitter to X.
Okay, sorry. Got it, now making a note, will share at last day.

**Comment by MastanSayyad** [comment]
@AkshitLakhera You have added level 1 and level 2 labels to this PR kindly only add level 1 and add me as a collaborator, we have sent an Email regarding this too

**Pull request merged**
