### PR TITLE
Enhance Appbar with Mode Toggle and Mobile Responsiveness for /blog Route

### PR DESCRIPTION
**Pull request by tejasbenibagde**
#ISSUE no.
`#29`

### PR Title:
Enhance Appbar with Mode Toggle and Mobile Responsiveness for /blog Route

### PR Description:
- **Appbar Update:** Replaced the existing Appbar with the new ui using `shadcn/ui` components, improving design consistency and usability.
- **Mode Toggle:** Added a dark/light/system mode toggle to allow users to switch between themes easily.
- **Mobile Responsiveness:** Made the `/blog` route fully mobile responsive, ensuring optimal viewing on smaller devices.

Here are some screenshots for better understanding: 

##**Overall ui**
FEAt

##**DropDown Menu Avatar**
Capture3

##**DropDown Menu ModeToggle**
Capture

##**Light Mode**
Capture2

Let me know if any further changes are required!

### CODE REVIEW

**Comment by tejasbenibagde** [comment]
@AkshitLakhera Please take a look at this and add the tags gssoc-ext, any one of the _levels(i.e level1, level2 or level3)_ and hactoberfest-accepted.

**Comment by tejasbenibagde** [comment]
@AkshitLakhera, I understand that you have a specific design in mind for the navbar. However, this PR primarily focuses on implementing the theme modes (dark/light/system).

Please consider merging this for now, and I’ll immediately begin adjusting the navbar to align with your design.

Let me know if that works for you!

**Comment by AkshitLakhera** [comment]
@

> @AkshitLakhera, I understand that you have a specific design in mind for the navbar. However, this PR primarily focuses on implementing the theme modes (dark/light/system).
> 
> Please consider merging this for now, and I’ll immediately begin adjusting the navbar to align with your design.
> 
> Let me know if that works for you!

fine

**Comment by tejasbenibagde** [comment]
please add the hactoberfest and gssoc tags :)

**Comment by tejasbenibagde** [comment]
@AkshitLakhera I'm opening a new issue related to the Navbar design please merge my PR so that I can start working on that one too. :)

**Comment by AkshitLakhera** [comment]
@tejasbenibagde  
Hey , Remove this  toggle from signin/up functionality .
image

**Comment by tejasbenibagde** [comment]
> @tejasbenibagde  
> Hey , Remove this  toggle from signin/up functionality .
> image.
> It is not looking good.
> 

Bro try to understand what I'm saying. I merely added the theming and updated some ui components. All the bugs that that are caused due to this can be addressed in the new PR. And I will be fixing the problems caused by my updates so it's not even like I'm running from my responsibility. 

If you have the question why I'm not doing this in the same PR is because most of the times I do this it creates the merge conflicts.

**Comment by tejasbenibagde** [comment]
Just merge I'll start working on it as soon as you merge it.

**Comment by AkshitLakhera** [comment]
> Just merge I'll start working on it as soon as you do it.

Okay fine, @tejasbenibagde bro  don't take me wrong here I was n't getting clarity that's why   I was asking you.

**Pull request merged**
