### PR TITLE
Authentication page

### PR DESCRIPTION
**Pull request by ayushrana83**
Signin / signup ui update

### CODE REVIEW

**Comment by AkshitLakhera** [comment]
see there is error here 
image
 that's why it is showing problem in deploying.

**Comment by AkshitLakhera** [comment]
Please avoid committing unnecessary changes to package-lock.json and pnp.yml. If you didn't intentionally update dependencies, consider reverting changes in those files. If you made updates, please ensure they are relevant to the task at hand.

**Comment by ayushrana83** [comment]
Sorry for the inconvenience . Changes were made in this file due to FarmUi . such as pnmp-lock.yaml file was added .
Can you tell me all the errors ? So , i can fix them.

**Comment by AkshitLakhera** [comment]
> Sorry for the inconvenience . Changes were made in this file due to FarmUi . such as pnmp-lock.yaml file was added . Can you tell me all the errors ? So , i can fix them.

see I have pasted  image which is vercel showing in it's deployment dashboard

**Comment by ayushrana83** [comment]
It was just an extra react dependency imported . I corrected it.

**Comment by AkshitLakhera** [comment]
> It was just an extra react dependency imported . I corrected it. Anthing else except that?

just push the latest changes from your side

**Comment by AkshitLakhera** [comment]
@ayushrana83  Perfect.I just want one improvement 
Screenshot from 2024-10-05 12-24-18
make sure only this changes when we toggle btw signup/ and sigin , don't open it separately.It will look more pleasing.

**Comment by ayushrana83** [comment]
Means left side of both components (signup , signin ) should be similar like signup page ?

**Comment by AkshitLakhera** [comment]
> Means left side of both components (signup , signin ) should be similar like signup page ?
> 
Yes ,I only want that  signup/sigin form to change rest left side should remain same in both case.

**Comment by AkshitLakhera** [comment]
@ayushrana83  Great job ,Everything is  perfect.

**Comment by ayushrana83** [comment]
Great.

**Comment by AkshitLakhera** [comment]
@ayushrana83  ayush I have reverted those changes, your this pr is merged acc to gssoc,I want you to raise a new issue and fix that auth part acc to light theme.Because it is not looking good when system theme is light.Or you can either make signup/in part with default theme as dark.

**Comment by ayushrana83** [comment]
this is how it looks
new

**Comment by AkshitLakhera** [comment]
> this is how it looks new you made changes ?
raise new pr.

**Pull request merged**
